services:

  dds_router:
    image: husarnet/dds-router:v1.0.0
    network_mode: host
    ipc: host
    volumes:
      - ./router-config-pc.yaml:/config.yaml
    command: ddsrouter -c /config.yaml -r 10

  # ros2-node:
  #   image: husarion/ros2-demo-nodes:humble
  #   network_mode: host
  #   ipc: host
  #   environment:
  #     - ROS_DOMAIN_ID=1
  #   command: ros2 run demo_nodes_cpp talker

  rviz:
    image: husarion/rviz2:galactic
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rbxl.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=1

  joy2twist:
    image: husarion/joy2twist:humble
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    environment:
      - ROS_DOMAIN_ID=1
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml

  mapping:
    image: husarion/slam-toolbox:humble
    container_name: slam-toolbox
    network_mode: host
    ipc: host
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
      - ./maps:/maps
    environment:
      - ROS_DOMAIN_ID=1
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}