services:

  dds_router:
    image: husarnet/dds-router:v1.0.0
    network_mode: host
    ipc: host
    volumes:
      - ./router-config-rosbot.yaml:/config.yaml
    command: ddsrouter -c /config.yaml -r 10

  # ros2-node:
  #   image: husarion/ros2-demo-nodes:humble
  #   network_mode: host
  #   ipc: host
  #   command: ros2 run demo_nodes_cpp listener

  rplidar:
    image: husarion/rplidar:humble
    network_mode: host
    ipc: host
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  rosbot-xl:
    image: husarion/rosbot-xl:humble
    network_mode: host
    ipc: host
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-False}

  microros:
    image: microros/micro-ros-agent:humble
    network_mode: host
    ipc: host
    command: udp4 --port 8888