version: v3.0

allowlist:
  
  - name: "*"

participants:

  - name: LocalParticipant
    kind: local
    domain: 1

  - name: RemoteParticipant
    kind: initial-peers
    listening-addresses:
      - domain: master
        port: 11811
    connection-addresses:
      - domain: rosbot-xl
        port: 11811